# Generated by Django 5.2.3 on 2025-06-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_info',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
    ]
